apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud
spec:
  template:
    metadata:
      labels:
        app: fraud
    spec:
      containers:
      - name: fraud
        image: leonespartano/fraud:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: kube
  selector:
    matchLabels:
      app: fraud