server:
  port: 8087

spring:
  application:
    name: notification

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true